name: Compile Arduino Sketches
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: arduino/compile-sketches@v1.1.0
    - name: WMS_Code/code__CCD_.ino
      run: ./WMS_Code/code__CCD_.ino
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
